name: buma_hris
description: "HRIS Application for BUMA"

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local dependencies
  core:
    path: ../../packages/core
  shared_dependencies:
    path: ../../packages/shared_dependencies

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Inherited dev dependencies
  flutter_lints:

flutter:
  uses-material-design: true
