name: shared_dependencies
description: Defines versions of shared dependencies.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  # UI
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^2.0.0

  # Icon generation
  flutter_launcher_icons: ^0.13.1
