name: shared_dependencies
description: Defines versions of shared dependencies.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  # UI
  flutter_screenutil: ^5.9.0

  # Routing
  auto_route: ^7.8.4

dev_dependencies:
  flutter_lints: ^2.0.0

  # Code generation
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

  # Icon generation
  flutter_launcher_icons: ^0.13.1
