name: resources
description: Centralizes and manages all static assets, including images, icons, and fonts files, for consistent and efficient access throughout the app.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Local dependencies
  shared_dependencies:
    path: ../../packages/shared_dependencies

  # Inherited Dependencies
  ## Routing
  auto_route:
  ## UI
  flutter_svg:

dev_dependencies:
  # Inherited DEV Dependencies
  ## Code generation
  build_runner:
  flutter_gen_runner:
  ## Others
  flutter_lints:

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  assets:
    - assets/images/
